INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES (101, 'Single', 'A cozy room for one person', 1, 100.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(102, 'Double', 'A comfortable room for two people', 2, 150.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(103, 'Suite', 'A luxurious suite with a living area', 4, 300.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(104, 'Family', 'A spacious room for families', 5, 200.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(105, 'Deluxe', 'An elegant room with premium amenities', 2, 250.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(106, 'Single', 'A cozy room for one person', 1, 100.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(107, 'Double', 'A comfortable room for two people', 2, 150.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(108, 'Suite', 'A luxurious suite with a living area', 4, 300.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(109, 'Family', 'A spacious room for families', 5, 200.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(110, 'Deluxe', 'An elegant room with premium amenities', 2, 250.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(111, 'Single', 'A cozy room for one person', 1, 100.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(112, 'Double', 'A comfortable room for two people', 2, 150.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(113, 'Suite', 'A luxurious suite with a living area', 4, 300.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(114, 'Family', 'A spacious room for families', 5, 200.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(115, 'Deluxe', 'An elegant room with premium amenities', 2, 250.00, 'DISPONIBLE', 'NO');

INSERT INTO GUEST (DOC_TYPE, DOC_NUMBER, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('DNI', '12345678A', 'John', 'Doe', 'j.doe@email.com', '555-1234', '123 Main St', 'Anytown', 'USA');

INSERT INTO GUEST (DOC_TYPE, DOC_NUMBER, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('DNI', '87654321B', 'Jane', 'Smith', 'jsmith@email.com', '555-5678', '456 Elm St', 'Othertown', 'USA');

INSERT INTO GUEST (DOC_TYPE, DOC_NUMBER, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('DNI', '11223344C', 'Alice', 'Johnson', 'alice.jhonson@amail.com', '555-9012', '789 Oak St', 'Sometown', 'USA');

INSERT INTO GUEST (DOC_TYPE, DOC_NUMBER, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('DNI', '44332211D', 'Bob', 'Brown', 'bob.brown@wmail.com', '555-3456', '321 Pine St', 'Anycity', 'USA');

INSERT INTO GUEST (DOC_TYPE, DOC_NUMBER, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('DNI', '55667788E', 'Charlie', 'Davis', 'c.davis@omail.com', '555-7890', '654 Cedar St', 'Othercity', 'USA');

INSERT INTO GUEST (DOC_TYPE, DOC_NUMBER, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('DNI', '99887766F', 'Eve', 'Miller', 'e.miller@email.com', '555-2345', '987 Spruce St', 'Sometown', 'USA');

INSERT INTO GUEST (DOC_TYPE, DOC_NUMBER, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('DNI', '66778899G', 'Frank', 'Wilson', 'fr.wilson@smail.com', '555-6789', '321 Birch St', ' Anytown', 'USA');