INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES (101, 'Single', 'A cozy room for one person', 1, 100.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(102, 'Double', 'A comfortable room for two people', 2, 150.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(103, 'Suite', 'A luxurious suite with a living area', 4, 300.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(104, 'Family', 'A spacious room for families', 5, 200.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(105, 'Deluxe', 'An elegant room with premium amenities', 2, 250.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(106, 'Single', 'A cozy room for one person', 1, 100.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(107, 'Double', 'A comfortable room for two people', 2, 150.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(108, 'Suite', 'A luxurious suite with a living area', 4, 300.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(109, 'Family', 'A spacious room for families', 5, 200.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(110, 'Deluxe', 'An elegant room with premium amenities', 2, 250.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(111, 'Single', 'A cozy room for one person', 1, 100.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(112, 'Double', 'A comfortable room for two people', 2, 150.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(113, 'Suite', 'A luxurious suite with a living area', 4, 300.00, 'DISPONIBLE', 'NO');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(114, 'Family', 'A spacious room for families', 5, 200.00, 'DISPONIBLE', 'SI');

INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, ROOM_DESCRIPTION, ROOM_CAPACITY, ROOM_PRICE, ROOM_AVAILABILITY, IS_PET_FRIENDLY)
VALUES(115, 'Deluxe', 'An elegant room with premium amenities', 2, 250.00, 'DISPONIBLE', 'NO');


INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('John', 'Doe', 'jdoe@mail.com', '1234567890', '123 Main St', 'Anytown', 'USA');

INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('Jane', 'Smith', 'jsmith@mail.com', '0987654321', '456 Elm St', 'Othertown', 'USA');

INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('Alice', 'Johnson', 'ajhonson@mail.com', '5551234567', '789 Oak St', 'Sometown', 'USA');

INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('Bob', 'Brown', 'bbrown@mail.com', '4449876543', '321 Pine St', 'Anycity', 'USA');

INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('Charlie', 'Davis', 'cdavis@mail.com', '3335556789', '654 Cedar St', 'Othercity', 'USA');

INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, CITY, COUNTRY)
VALUES ('Eve', 'Miller', 'emiller@mail.com', '2226667890', '987 Birch St', 'Sometown', 'USA');